### ISSUE TITLE
By default installed or not?

### ISSUE THREAD

**Issue by melroy89** [OCA/l10n-netherlands#117]
Odoo has already some default Dutch stuff (like ledger accounts, VAT, etc.). 

So is this l10n-netherlands by default installed in Odoo (it's different than `l10n_nl` add-on)? If not, what does it really add more?

And will this module be added by default in Odoo v11?

Kind regards,
Melroy

**Comment by hbrunn** [comment]
you should read up on how odoo and the oca works and what their relationship is. This is not the right place to explain basics, start at https://odoo-community.org/
