### ISSUE TITLE
 l10n_nl_tax_statement -  4a & 4b turnover negative

### ISSUE THREAD

**Issue by CasVissers-360ERP** [OCA/l10n-netherlands#125]
Hi,

When creating a tax statement the turnover in 4a & 4b are shown as a negative amount. I think this should be positive, surely because the tax in 4a&4b is shown as a positive number.

Cas

**Comment by yung-wang** [comment]
Made a test in V10 with and agree. It is best to make the turnover amount positive. Can we make the display of the turnover amount into an absolute?

**Comment by astirpe** [comment]
Sure, I will fix it next week. Thank you!

**Comment by astirpe** [comment]
5a is the sum of 1a through 4b.
Is the actual calculation of 5a correct?

In case I display a positive amount of 4a and 4b, shall I also change the calculation of 5a?

**Comment by CasVissers-360ERP** [comment]
The calculation of 5a is correct. Its just the case of displaying the amounts as positive.

**Comment by astirpe** [comment]
@CasVissers can you check the PR #127 ?

**Comment by CasVissers-360ERP** [comment]
@astirpe 
Looks good thus far. 
One thing I missed in my ticket was 2a, this fix should apply to 2a as well.

**Comment by astirpe** [comment]
@CasVissers shouln't be applied for all the values, then? From 1a to 4b, if the omzet has a different sign than btw, invert the omzet sign. What do you think?

**Comment by CasVissers-360ERP** [comment]
@astirpe 
You are right, I agree that's the best solution.

**Comment by astirpe** [comment]
Done, can you check?

**Comment by CasVissers-360ERP** [comment]
Done, issue closed.
