### ISSUE TITLE
report_tax_statement not working

### ISSUE THREAD

**Issue by elperrofarelo** [OCA/l10n-netherlands#142]
Error in line 67:         <t t-call="report.html_container">
Should be:         <t t-call="web.html_container"> due to the changes in V11
But after changing this, the report is created but empty

**Comment by astirpe** [comment]
@elperrofarelo are you testing the actual V11 https://github.com/OCA/l10n-netherlands/tree/11.0/l10n_nl_tax_statement module already merged? Or the latest open pull request?
Can you provide us some more info?

**Comment by astirpe** [comment]
Even better: can you copy and past the entire stacktrace log?

**Comment by astirpe** [comment]
https://github.com/OCA/l10n-netherlands/pull/126#issuecomment-358682593

**Comment by astirpe** [comment]
This issue can be closed. The fix was merged.
