### ISSUE TITLE
Dutch basic configurations

### ISSUE THREAD

**Issue by diellenne** [OCA/l10n-netherlands#2]
Proposal for the implementation of a module containing basic configurations to fit the general customs and traditions of the Netherlands. The idea is to create a module to collect all the settings and configurations that are too small to have a dedicated module: the discussion about what has to be included in this module and what doesn't is open...

**Comment by diellenne** [comment]
Some ideas to start:
- Currency symbol in reporting before amounts
- Decimal separators automatically set to the form 1.000,00

**Comment by RoelAdriaans** [comment]
We adapted the oca/partner-contact/partner_firstname module to have extra fields.

We added initials, given name, preposition and a last name. (Initialen, voornaam, voorvoegsel and a lastname). This generates a name and a formal name, where the name field uses the given name, and the formal name uses the initials.

**Comment by diellenne** [comment]
Sounds good but I was thinking to put in this module just the configurations you usually do from the interface; so you don't have to do them manually. This is my idea but we can discuss about it...

About your module: it seems really useful and I think it deserves a dedicated module (e.g. l10n_nl_partner_firstname). If you want you can create a new proposal (issue) to discuss it and we can add it to the roadmap in order to add it in the Dutch localization project.

**Comment by hbrunn** [comment]
@RoelAdriaans-B-informed you might want to look at #3, that does most of what you named and the rest can be done with a few very simple overrides

**Comment by diellenne** [comment]
This topic was mentioned today in the meeting: let's reopen this discussion; any Idea is welcome!
