### ISSUE TITLE
Odoo 9 Sprint - Shared goals

### ISSUE THREAD

**Issue by Fuchur777** [OCA/l10n-netherlands#20]
Odoo 9 sprint shared goals for September 9th 2015.

**Comment by woepwoep** [comment]
Graag zou ik iDEAL willen inbrengen (pos_ideal)
Bij Therp zit iemand die daar verstand van heeft (Holger Brunn) misschien dat Holger ook mee wil doen?
Zelf heb ik ook diverse iDEAL koppelingen gerealiseerd in TYPO3 (www.typo3.org) o.a. ing_advanced en rabo_omnikassa.
Als basis zouden we https://github.com/thegreatnew/python-ideal kunnen gebruiken.
R

**Comment by ghost** [comment]
UBL import en export van facturen op een digitale manier. Geen PDF's overtypen maar direct een factuur aanmaken. http://www.ublketentest.nl/ voor uitleg over formaat. 
Initiatief van de Nederlandse overheid en ondersteund door unit4, snelstart, yuki en tig anderen.

**Comment by diellenne** [comment]
Hi All,

the meeting was really nice: there was a lot of things to talk and discuss about! In name of OCA I'd love thank all the persons that joined this first 'Odoo Dutch Community meeting' hoping that in the future our community will become bigger and bigger!

I'm updating the issue section of the project with the main topics we discussed so we can use them as discussion board and get everyone involved also people who where not here today.

D
