### ISSUE TITLE
l10n_nl_tax_statement: Clearing the tax account moves included in the Nederlands BTW Statement to a dedicated payable/receivable (suspense) account when posting the statement

### ISSUE THREAD

**Issue by Binformed** [OCA/l10n-netherlands#223]
Hi,

It would be a great enhancement, if when posting a BTW Statement, the option is given to clear all the tax account moves, which are included in the statement, to a dedicated payable/receivable (suspense) account. Subsequently the tax account moves are reconciled on the tax accounts, leaving only the journal item on the dedicated suspense account open to be reconciled with the (bank) payment. The status of the BTW Statement should then be Posted & Reconciled (Draft - Posted & Reconciled - Final). If the option is not used the status should be Posted (Draft - Posted - Final).

Additionally, when the option to clear the concerning tax account moves was been used when posting the BTW Statement, the resulting journal entry and reconciliations are automatically reversed when statement is reset to draft. The accounting date of the reversal should be in the current period and the 2 journal items on the dedicated suspense account should be automatically reconciled.
If the statement was only posted, when resetting the statement to draft, the user should get a notification to consider the manual journal entry and reconciliations (if applicable).

![screen shot 2019-02-28 at 17 20 14](https://user-images.githubusercontent.com/32832163/53627785-a8731f80-3c09-11e9-938d-b1657a867674.png)

![screen shot 2019-03-01 at 10 00 46](https://user-images.githubusercontent.com/32832163/53629610-42d56200-3c0e-11e9-85b7-c85861d11057.png)

![screen shot 2019-03-01 at 10 42 45](https://user-images.githubusercontent.com/32832163/53629838-dd35a580-3c0e-11e9-969c-8ead1b046457.png)

If further information is needed, please contact me.

Thanks in advance for your reply.

Regards,

Robert Wever

**Comment by Binformed** [comment]
If the option is not used the status should be Posted **(Draft - Posted - Reconciled).** -> (Draft - Posted - Final)

**Comment by astirpe** [comment]
@yung-wang what do you think about this?

**Comment by yung-wang** [comment]
@Binformed I haven't heard any customer asking for this feature. It sounds nice. I would suggest that a Gold Partner as B-Informed with own developers to contribute on the Dutch Localisation with this new feature by creating Pull Request with the new code. That would be great, very supportive to the OCA and helping to make Odoo bigger in The Netherlands. Please help out.

**Comment by Binformed** [comment]
I will discuss internally what the possibilities are to contribute to this enhancement.

Robert

**Comment by yung-wang** [comment]
@Binformed That would be great if you can contribute. Together we can make Odoo great in The Netherlands. The more others can contribute, the better. With all our knowledge, skills and experience we can make this successful. Let's be part of this community!
