### ISSUE TITLE
XAF export no starting balance

### ISSUE THREAD

**Issue by krijn1981** [OCA/l10n-netherlands#225]
We runned a XAF file (the V9 version) through a XAF analyser. But it look like there is not starting balance data. I am not a technical guy but what I can see in the code we only talking about start- and end-date of the fiscal year.

But as properly every knows Odoo has left since V8 the concept of fixed periods.
So since V8 there is not opening period (0). Therefore it will not appear anymore in the Audit-file.

Can somebody confirm that my findings are match with the code.
I see call of start- and end date in the V9/10/11 versions. but not a the "creation" of a period 0/opening/starting balance.

As my understandings the XAF module is only fetching the mutations of the exported year.

**Comment by Binformed** [comment]
Hi OCA, can the previous comment be confirmed?

If yes, will it be fixed as more and more clients are reporting the same issue.

I would be nice to at least receive a confirmation about the code.

Thanks in advance.

**Comment by astirpe** [comment]
Here is the code you are mentioning https://github.com/OCA/l10n-netherlands/blob/9.0/l10n_nl_xaf_auditfile_export/views/templates.xml#L104-L106 and that is the confirmation that the starting balance is not yet implemented.

**Comment by krijn1981** [comment]
Hi, yes i see @astirpe is there a planning to create this?
Currently with XAF file the account can not fully his checkup by his XAF/controlling software.

**Comment by astirpe** [comment]
@krijn1981 I'm not aware about any plan to add the starting balance. You may ask the authors of the module to know whether someone developed this. If you want you could also try to contact the company I'm working for and arrange an agreement for the developments.
