### ISSUE TITLE
CBS / Intrastat module for The Netherlands

### ISSUE THREAD

**Issue by andreschenkels** [OCA/l10n-netherlands#23]
Based on the OCA intrastat base we should provide a correct Intrastat report

**Comment by hbrunn** [comment]
https://github.com/OCA/l10n-netherlands/pull/57

**Comment by astirpe** [comment]
CBS and ICP: are we talking about different things?

- Centraal Bureau voor de Statistiek (CBS)
- Opgaaf intracommunautaire prestaties (ICP)

**Comment by ploegvde** [comment]
Yes those are different things. CBS is for the Dutch Statistics Bureau and ICP is for the Dutch Tax authorities. Reports are completely different.

**Comment by astirpe** [comment]
Are we considering to reopen this issue? Would CBS reports be of interest for the Dutch community?

**Comment by ploegvde** [comment]
I think the would. WE have made something recently, The CBS output is a CSV file (yes they are that old fashioned) That you have to upload to the CBS website.

The only thing is that the content contains some fixed values, that are fixed for my customer, but can we different for other customer. But i can share if you want.

**Comment by astirpe** [comment]
@ploegvde if you want, you can open a PR to OCA proposing that module, we will continue the discussion there. It would be great!
For making it generic and OCA guidelines compliant we can join the efforts.
What do you think?

**Comment by ploegvde** [comment]
Ok, i will do that today.
