### ISSUE TITLE
l10n_nl_bsn: searching on BSN without dots

### ISSUE THREAD

**Issue by thomaspaulb** [OCA/l10n-netherlands#231]
I have seen that the `l10n_nl_bsn` module reformats the BSN by placing dots between the numbers in certain places, eg. `123.45.678` instead of `12345678`. However, when reading for example CSV files with BSN data and trying to match on it, the data will often be without those dots and thus the matching/searching on BSN will not work without extra modifications. Searching on a number without dots will also not work well in the regular Odoo "advanced search".

To me, the dots are formatting and the BSN should not be stored with them; rather there should be something like a BSN widget that shows the formatted BSN but the stored number is still vanilla. This is IMO the "right" way and will also aid in searching and comparing.

Any opinions on this?

**Comment by astirpe** [comment]
Yes, I agree.
Alternatively we could implement a [search method](https://github.com/odoo/odoo/blob/12.0/odoo/fields.py#L157) for the bsn field. This will fix the Odoo "advanced search" and probably will also fix the importing by CSV.

**Comment by thomaspaulb** [comment]
True, but such a search method should then be accompanied by either of these three:

1. A migration script that adds dots to existing BSN's, very strict enforcing that dotless BSN's don't enter the database and searching on BSN's with dots only
2. Some Postgres trick that allows a `where` search on a transform of the BSN value to something without dots (i dont know if this exists)
3. A stored, indexed computed field without dots that the search operates on

**Comment by astirpe** [comment]
@thomaspaulb the above three points are not necessary IMO. The search method must allow the search on both dotted and not-dotted records, so no need of migration scripts or extra computed fields.

**Comment by thomaspaulb** [comment]
Ah yes, my mind missed the option of searching for dotted as well as non-dotted. That should also do it.
