### ISSUE TITLE
l10n_nl_account_credit_control dependency error

### ISSUE THREAD

**Issue by pjkersten** [OCA/l10n-netherlands#236]
l10n_nl_account_credit_control depends on account_credit_control (OCA/credit-control), which is 12.0. In 11.0 it is non existent.

**Comment by astirpe** [comment]
@pjkersten `account_credit_control` for 11.0 is here: https://github.com/OCA/account-financial-tools/tree/11.0

**Comment by pjkersten** [comment]
@astirpe Didn't see that. Thanks.
