### ISSUE TITLE
Tax Statement and ICP: allow a fiscal unit to do a tax statement for all the child companies. For the ICP the Totals of access to the childs.

### ISSUE THREAD

**Issue by yung-wang** [OCA/l10n-netherlands#237]
According the Dutch Tax Authority, as a fiscal unit, you can do 1 tax statement for all companies including the child companies.

In the current module, you can only see your the tax statement of the company you're logged in. In Enterprise, you can do a statement of all the companies, by selecting them when you're logged in into the parent company. It would be nice to have the same functionality in this module.

https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/hoe_werkt_de_btw/voor_wie_geldt_de_btw/fiscale_eenheid/

For the ICP, the fiscal unit is allowed write down the totals of the ICP of all the companies.
https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/zakendoen_met_het_buitenland/goederen_en_diensten_naar_andere_eu_landen/opgaaf_icp/opgaaf_icp_door_fiscale_eenheden

Requirement:
- The same Tax codes labels for all the companies.
- Company must be in The Netherlands

**Comment by astirpe** [comment]
The ICP reports must be created separately for each company in any case, right?

**Comment by astirpe** [comment]
@yung-wang could you check https://github.com/OCA/l10n-netherlands/pull/238?

**Comment by yung-wang** [comment]
fixed in https://github.com/OCA/l10n-netherlands/pull/238
