### ISSUE TITLE
Postcode API

### ISSUE THREAD

**Issue by nielsmiddeldorp** [OCA/l10n-netherlands#25]
This is a great addition for Dutch users. Now it relies on a single provider. It would also be great to be able to use other providers like: [overheid.io](https://overheid.io/documentatie/bag), [postcodes.nl](https://www.postcodes.nl/webservice/technical/address) or even directly from the government via: [kadaster](http://www.kadaster.nl/web/artikel/producten/BAG-Bevragen.htm). This way it would be less dependent and more robust and flexible.

**Comment by StefanRijnhart** [comment]
Sure. If someone wants to implement this for other providers, it should be easy to refactor and add a generic interface layer.

**Comment by StefanRijnhart** [comment]
@nielsmiddeldorp are you planning to work on this? Otherwise this issue may probably be closed.

**Comment by mgielissen** [comment]
@StefanRijnhart There is a new Postcode API 2.0. V1.0 wil discontinued at March 1, 2016

**Comment by mgielissen** [comment]
Any news about API 2.0?

**Comment by hbrunn** [comment]
@mgielissen the code is done for a while already, but not yet published on pypi: https://github.com/steffex/pyPostcode/issues/11 - so this is rather an issue of the underlying library than of the odoo addon
