### ISSUE TITLE
Dutch mis builder reports? PnL  and Balance sheet

### ISSUE THREAD

**Issue by ayushin** [OCA/l10n-netherlands#256]
Hi guys,

I was wondering why there are no PnL and Balance sheet MIS builder reports for Holland?

The community seems to be pretty big and even BTW & ICP  modules are available but not MIS reports?

Am I missing something?

**Comment by astirpe** [comment]
In the Netherlands, by law there's no standard mandatory Chart Of Accounts. It means that each company is free to adopt its own customized COA. Since P&L and Balance Sheet are strictly depending on the COA, there's not an easy way to create such generic "MIS builder reports" module.

**Comment by ayushin** [comment]
Yes, I realise that. But there's an elaborate chart of accounts that comes with Odoo by Onestein - "Netherlands - Accounting"

Should not be too difficult to have two simple MIS reports Balance sheet and PnL for that chart?

Should not be too much work for somebody who is proficient with MIS builder and will be a great help for the community.

**Comment by astirpe** [comment]
@ayushin The reports you are mentioning are not in my todo list at the moment. Let's see if someone else can help you...

**Comment by astirpe** [comment]
Proposed in https://github.com/OCA/l10n-netherlands/pull/263

**Comment by gjotten** [comment]
@hbrunn AFAICS this issue can be closed since it's been addressed in your module.
