### ISSUE TITLE
Whiteworks import

### ISSUE THREAD

**Issue by StefanRijnhart** [OCA/l10n-netherlands#28]
Hi,

by customer demand, I have made a module that imports .xlsx files with contacts and invoices generated by Whiteworks CRM and accounting. https://www.whiteworks.nl/. It can be used as the starting point of a one time migration or as a periodic process. As Whiteworks is a very local player in the Netherlands, we could host the module in this project if there is any interest. Let me know and I will make a PR.

**Comment by astirpe** [comment]
Hello @StefanRijnhart, where can we find the code of the module you mentioned? I'm curious to see it and I could try to find out if there could be of any interest for the Dutch localization.
Thank you!

**Comment by StefanRijnhart** [comment]
Code is in a customer's repo at this moment, sorry. I was asking, do you want this functionality and I'll give you the code. Now you are saying, give me the code and we'll tell you if we want the functionality (which makes less sense to me, no offense). It confirms my suspicion that the functionality is not that compelling (I never heard of Whiteworks before I was asked to do this). You know that it takes time to cook up the readme and prepare the PR so if you don't mind I'd rather wait until that is actually useful for someone.

**Comment by StefanRijnhart** [comment]
By the way, if you think this is a weird conversation, I agree but we have have been burned before by a Onestein guy on this project because we just proposed code without a notification or a discussion beforehand wether the proposed code 'fit in the project's roadmap'.
