### ISSUE TITLE
XAF auditfile optional year in periods

### ISSUE THREAD

**Issue by jvOrsouw** [OCA/l10n-netherlands#289]
My customer doesn't get the move-lines when the auditfile is imported into Unit4 audition or FDS. This is caused by the way the periods are build: if a period is 'year + month', their program doesn't get it. 
Can the period be changed to just 2 characters for just the months, or maybe this option can be made optional?

**Comment by NL66278** [comment]
@jvOrsouw Do you have the possibility to patch the code? In that case it would be easy to point out how to leave out the year. Otherwise it would take some programming to create a Pull Request.

**Comment by jvOrsouw** [comment]
hi @NL66278 , yes I have the possibility to patch the code through direct SSH access to the server. I think I'll be able to change the period myself by updating the 'get_period_number'.

**Comment by NL66278** [comment]
@jvOrsouw That is indeed the place to act. The date is passed to the method in ISO format: "2020-02-01",.

period_id = date[5:7] should do the trick.

Note that from version 12.0 the logic of get_period_number changed completely.

**Comment by astirpe** [comment]
Shall the 2 characters period be applied only for Unit4? Or could it be a general requirement?

**Comment by jvOrsouw** [comment]
@astirpe as fas as I'm concerned, it could be a general requirement. However, it might raise issues for companies with a fiscal period other than january-december. If f.e. the fiscal period is from july to june, and the periods are 07-08-....-06, this might be sorted incorrectly? 
@NL66278 I noticed the change in get_period_number. As the client is in the process of migrating to v13, I'll keep in mind this will also influence this module.
