### ISSUE TITLE
l10n_nl_xaf_auditfile_export error while generating auditfile CW - Curaçao

### ISSUE THREAD

**Issue by mlamie** [OCA/l10n-netherlands#300]
**module**: l10n_nl_xaf_auditfile_export
**version**: 12.0.1.0.1

**Steps to reproduce**
Click on Generate auditfile.

**Current behavior**
getting error
Element '{http://www.auditfiles.nl/XAF/3.2}taxRegistrationCountry': [facet 'enumeration'] The value 'CW' is not an element of the set {'AD', 'AE', 'AF', 'AG', 'AI', 'AL', 'AM', 'AN', 'AO', 'AQ', 'AR', 'AS', 'AT', 'AU', 'AW', 'AX', 'AZ', 'BA', 'BB', 'BD', 'BE', 'BF', 'BG', 'BH', 'BI', 'BJ', 'BM', 'BN', 'BO', 'BR', 'BS', 'BT', 'BV', 'BW', 'BY', 'BZ', 'CA', 'CC', 'CD', 'CF', 'CG', 'CH', 'CI', 'CK', 'CL', 'CM', 'CN', 'CO', 'CR', 'CS', 'CU', 'CV', 'CX', 'CY', 'CZ', 'DE', 'DJ', 'DK', 'DM', 'DO', 'DZ', 'EC', 'EE', 'EG', 'EH', 'ER', 'ES', 'ET', 'FI', 'FJ', 'FK', 'FM', 'FO', 'FR', 'GA', 'GB', 'GD', 'GE', 'GF', 'GH', 'GI', 'GL', 'GM', 'GN', 'GP', 'GQ', 'GR', 'GS', 'GT', 'GU', 'GW', 'GY', 'HK', 'HM', 'HN', 'HR', 'HT', 'HU', 'ID', 'IE', 'IL', 'IM', 'IN', 'IO', 'IQ', 'IR', 'IS', 'IT', 'JM', 'JO', 'JP', 'KE', 'KG', 'KH', 'KI', 'KM', 'KN', 'KP', 'KR', 'KW', 'KY', 'KZ', 'LA', 'LB', 'LC', 'LI', 'LK', 'LR', 'LS', 'LT', 'LU', 'LV', 'LY', 'MA', 'MC', 'MD', 'MG', 'MH', 'MK', 'ML', 'MM', 'MN', 'MO', 'MP', 'MQ', 'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'MX', 'MY', 'MZ', 'NA', 'NC', 'NE', 'NF', 'NG', 'NI', 'NL', 'NO', 'NP', 'NR', 'NU', 'NZ', 'OM', 'PA', 'PE', 'PF', 'PG', 'PH', 'PK', 'PL', 'PM', 'PN', 'PR', 'PS', 'PT', 'PW', 'PY', 'QA', 'RE', 'RO', 'RS', 'RU', 'RW', 'SA', 'SB', 'SC', 'SD', 'SE', 'SG', 'SH', 'SI', 'SJ', 'SK', 'SL', 'SM', 'SN', 'SO', 'SR', 'ST', 'SV', 'SY', 'SZ', 'TC', 'TD', 'TF', 'TG', 'TH', 'TJ', 'TK', 'TL', 'TM', 'TN', 'TO', 'TR', 'TT', 'TV', 'TW', 'TZ', 'UA', 'UG', 'UK', 'UM', 'US', 'UY', 'UZ', 'VA', 'VC', 'VE', 'VG', 'VI', 'VN', 'VU', 'WF', 'WS', 'YE', 'YT', 'ZA', 'ZM', 'ZW'}.

**Expected behavior**
It looks like the country code "CW" (for Curaçao) is rejected by the XAF specification format.
(even if "CW" is well defined in the ISO 3166 standard).

**Comment by astirpe** [comment]
Yes, that country code "CW" should be added in the `CountrycodeIso3166` list: https://github.com/OCA/l10n-netherlands/blob/12.0/l10n_nl_xaf_auditfile_export/data/XmlAuditfileFinancieel3.2.xsd#L693

@mlamie are you going to open a PR for that? Or do you need help?

**Comment by mlamie** [comment]
@astirpe Sorry, but I can't program (I do have IT Project Manager skills ;-)). Help on the subject is much appiciated.

**Comment by mlamie** [comment]
Can we also include the issue 254 which I opend earlier? See: https://github.com/OCA/l10n-netherlands/issues/254

**Comment by CasVissers-360ERP** [comment]
See #255 PR for version 10 will try to make a PR for version 12 and upwards sometime this week. Also the list of currencies should be improved.

**Comment by CasVissers-360ERP** [comment]
@mlamie See #301
