### ISSUE TITLE
[14.0] l10n_nl_tax_statement

### ISSUE THREAD

**Issue by bosd** [OCA/l10n-netherlands#312]
The version history (changelog) does not include the port to V14
https://github.com/OCA/l10n-netherlands/blob/7f2f147c43ae68b514e6328bce68f164a25fadd7/l10n_nl_account_tax_unece/readme/HISTORY.rst

**Comment by StefanRijnhart** [comment]
Not sure this is a problem. The migration entries are somewhat redundant for my part.

**Comment by bosd** [comment]
No problem at all. (just my ocd)
I created an issue, because I did'nt know where to raise attention to this item.
