### ISSUE TITLE
l10n_nl_xaf_auditfile_export Error during creation of audit file : too many fractional digits

### ISSUE THREAD

**Issue by MartinAarts** [OCA/l10n-netherlands#315]
We're trying to create an audit file of the 2020 fiscal year, but when trying to create the audit file, we get this error:
Element '{http://www.auditfiles.nl/XAF/3.2}amnt': [facet 'fractionDigits'] The value '40.800000000000004' has more fractional digits than are allowed ('2').

We can't find the booking that would cause this. Shouldn't this be rounded somewhere in this module?

**Comment by astirpe** [comment]
Could be field `balance` or field `amount_total`, since they are computed fields, and thus their values cannot be searched inside the db. You can try to round both of them. What version are you using?

**Comment by MartinAarts** [comment]
i've updated an hour ago to version 13.0.1.1.2.

Any hints on how to do the rounding?

**Comment by astirpe** [comment]
In file `views/templates.xml`, try to replace this line:

`<amnt><t t-esc="abs(l.balance)" /></amnt>`

with:

`<amnt><t t-esc="round(abs(l.balance), 2)" /></amnt>`


and replace line:

`<amnt><t t-esc="abs(l['balance'])" /></amnt>`

with:

`<amnt><t t-esc="round(abs(l['balance']), 2)" /></amnt>`

and then update the module.

If this is working I will open a PR to fix it.

**Comment by MartinAarts** [comment]
Thanks for your help, with the adjustments you suggested, the error changed to a different amount. So i had to change to more lines to get it to work, changed lines are:

 <amnt><t t-esc="round(m.amount_total, 2)" /></amnt>

and

<curAmnt><t t-esc="round(l.amount_currency, 2)" /></curAmnt>
