### ISSUE TITLE
Plotting a new roadmap

### ISSUE THREAD

**Issue by pankk** [OCA/l10n-netherlands#33]
Dear Dutch OCA community,

2016 is well underway and Odoo 9 has been released for a few months now.

Let's discuss which modules we want to update to 9 and which new modules would be nice to have for the Dutch market.

To name just a few:
- XAF audit file
- Ideal Payment
- KvK connector
- NL Configuration
- SBR / XBLR / BTW aangifte
- Tax: Werkkostenregeling
- NL Banking integration

As the last sprint was a success and a nice way to meet other Odoo developers, we plan to organize a sprint at the end of Q1 '16.

In preparation for this sprint it would be nice if we could have already developed some modules or upgraded some to 9, this so there are only real challenges left for the sprint ;)

So reply to this topic if you are considering:
- to add a module,
- to discontinue a module,
- on what module(s) you want to work,
- to contribute to this discussion in a constructive manner.

**Comment by andreschenkels** [comment]
Thnx for providing a new roadmap. I would love to do some work on XAF and Werkkosten. 
Am I missing the Tax report?

**Comment by pankk** [comment]
Dear all,

Please take some time to reply on this thread to collaborate together for better accounting in The Netherlands. This message was sent earlier but the replies are not sufficient yet. Once more, I request you to take a look at this. 
Many thanks, and I hope to hear from you, and see you soon during our sprint that we will organize on our location.

Kind regards,

Kevin Graveman

**Comment by ploegvde** [comment]
Funny, that we talk English in the Dutch localisation, but anyhow. I want to add some things that i find important for Dutch users;
- ICP aangifte rapportage en directe aangifte bij belastingdienst
- Bankafschrift import (is een OCA project)
- Betaalbestand naar bank (is een OCA project)
- Betaalbestand auto incasso (is een OCA project)
- Goed balans en W&V rapportages
- Opschonen/bijwerken huidige GB-schema
- Toevoegen inkoop belastingen inclusief BTW

I can't develop myself, but i want to help in any way as possible. So let me know me where i can help.

**Comment by mgielissen** [comment]
+1 for Tax report for v9c

**Comment by astirpe** [comment]
Based on the job of @alexis-via, the electronic invoicing based on UBL (Universal Business Language) standard.

**Comment by alexis-via** [comment]
@astirpe I plan to port my UBL/CII modules to v9, but only when I will have a stable structure on v8... and I will probably change the structure when the French standard on electronic invoicing will be published, which should happen in the coming weeks/months (no exact date has been set yet). In the meantime, I prefer to have only the modules for v8, because it's a pain to change the structure and datamodel in several versions.

**Comment by pankk** [comment]
Is anyone working on porting the ICP module?

**Comment by hbrunn** [comment]
intrastat is done in https://github.com/OCA/l10n-netherlands/pull/57

**Comment by melroy89** [comment]
Uh.. SBR/XBLR is still not done?
