### ISSUE TITLE
Generate Audit File - Max Length Issue

### ISSUE THREAD

**Issue by support-atharva** [OCA/l10n-netherlands#358]
## Module
XAF auditfile export - 14.0 Version

## Describe the bug
When we generate the Audit File, It throws an error for the Data Length.

## To Reproduce
**Affected versions**:
14.0

1. Generate Audit-file Export Record
2. Click on "Generate Auditfile" button.
3. Error: Element '{http://www.auditfiles.nl/XAF/3.2}bankAccNr': [facet 'maxLength'] The value has a length of '38'; this exceeds the allowed maximum length of '35'.

How can we solve this issue?

**Comment by CasVissers-360ERP** [comment]
@support-atharva 
Look for bank account numbers with a length > 35 and shorten them.

SELECT id, sanitized_acc_number FROM res_partner_bank WHERE LENGTH(sanitized_acc_number) > 35;

**Comment by astirpe** [comment]
@support-atharva did the solution proposed by Cas work for you? Can we close this issue?

**Comment by support-atharva** [comment]
@astirpe 

Thanks, Yes this works.
