### ISSUE TITLE
line 1653: b'xmlParseEntityRef: no name'

### ISSUE THREAD

**Issue by jerryBlueZebra** [OCA/l10n-netherlands#397]
## Module
XAF auditfile export 

## Describe the bug
When i try to generate a audit file it says: line 1653: b'xmlParseEntityRef: no name'

## To Reproduce
Generate a Audit file: Accounting -> Reports -> Audit file export

1. Accounting app
2. Reports
3. Audit file export

**Expected behavior**
Generate a Audit file

**Comment by gjotten** [comment]
To be blunt: this isn't a helpful issue. Which version of Odoo is this for? That's key information we're missing, which should be in the title, which isn't very descriptive anyway. Also, why is this a bug, according to you? OCA is a non-profit collective, not an on-call support team.

Anyway, the problem's with the data being parsed, hence the specific error. And while this is not necessarily a bug with the module itself, you're possibly looking at a lack of proper error management, which I've personally run into with this module as well. Them's the breaks.

When you try to generate an .xaf file with illegal characters you could for example run into this error. Ampersand ('&'), which I suspect is to be found in line 1653 of the temporary .xaf which gets deleted by the module, is one of these chars.

Some massaging of the module code on a testing environment should prevent the temporary .xaf from being deleted. That way you can hunt down the offending record. On the other hand, a query on illegal characters on for example your res.partner table might also solve your problem.

**Comment by jerryBlueZebra** [comment]
I see, thanks for the info.
