### ISSUE TITLE
[9.0] XAF audit file export fails with long login (E-Mail)

### ISSUE THREAD

**Issue by RoelAdriaans** [OCA/l10n-netherlands#71]
With the new 9.0 module, the export fails when the user doing the entries logs in with an emailadres.
The error message:

<pre>
:5228:0:ERROR:SCHEMASV:SCHEMAV_CVC_MAXLENGTH_VALID: Element '{http://www.auditfiles.nl/XAF/3.2}userID': [facet 'maxLength'] The value has a length of '37'; this exceeds the allowed maximum length of '35'.
:5228:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element '{http://www.auditfiles.nl/XAF/3.2}userID': 'p.pietjepuk@pietjepukenterprisesbv.nl' is not a valid value of the atomic type '{http://www.auditfiles.nl/XAF/3.2}IdentificationString35'.
</pre>

We are using google authentication, therefore we can't change the login.
Proposed solutions:
- Replace the login with the part before the @, if the login contains an @.
- Truncate the login to 35 characters.. This usually truncates the last part of the domain,
- Use the name, of another field?

If someone can give feedback, I can create a patch for this.

**Comment by hbrunn** [comment]
fixed by d9931e2
