### ISSUE TITLE
Local Netherlands Maintainers Team

### ISSUE THREAD

**Issue by diellenne** [OCA/l10n-netherlands#8]
Hi Everybody,

with new year is time to intensify the work on this project and to speed up the activities we should have a bigger maintenance team.
Who is interested in this activity can just reply to this post and I will be happy to organise a team big enough to never leave the project uncovered.
For some permission issues I cannot add directly new members but I will take care to forward the requests to the OCA administrators.

Cheers.

**Comment by StefanRijnhart** [comment]
Yes please. I am also proposing my colleague @holgerbrunn who is one of the more active reviewers in OCA overall. Note that as an OCA board member, I can actually assign the members until the issue with the permissions has been resolved.

**Comment by StefanRijnhart** [comment]
Oh wait, it's @hbrunn

**Comment by diellenne** [comment]
So for now I suggest to add to the Local Netherlands Maintainers Team:
- @StefanRijnhart 
- @hbrunn (Holger Brunn)
- @pankk (Kevin Graveman)

Obviously any other proposal will be highly appreciated. :+1: 

@StefanRijnhart, can you please add these users in the group? Thank you.

**Comment by ploegvde** [comment]
Sorry, I love to help. But i'm not a developer. Good luck guys!

**Comment by StefanRijnhart** [comment]
Done: checked that everyone has filed their CLA to the OCA and added these members to the maintainers team.

**Comment by diellenne** [comment]
Hi @erwin-bas-solutions,

thank you for your interest in the project! Also if you are not a developer I hope to see you active in it, there are thousand way to contribute: testing, bug reporting, functional review, translations, new modules proposal, documentation...everything will be really highly appreciated so feel free to join our community! :)

Cheers.

**Comment by diellenne** [comment]
@StefanRijnhart  :+1: 

I cannot find @hbrunn in the OCA Odoo instance: can you give a look why he is not present in the OCA members list? I'd like to have him in the Odoo system to keep the task status aligned.

**Comment by StefanRijnhart** [comment]
To answer your question, @dielenne: most partners are not users in the OCA database, and project members need to be users not partners. We are trying to fix that here: https://github.com/OCA/maintainers-tools/pull/47
